# workflow to build XO projects (indentlog, refcnt, reflect, ..)
# using custom docker container
#
# NOTES
# 1. GIT_TOKEN granted automatically by github.
#    has read permission on public resources + read/write permission on this repo
#
# 2. container built from [[https:github.com:rconybea/docker-xo-builder]]
#
# 3. runner filesystem as build completes:
#
#      {{github.workspace}} (looks like will be [/home/runner/work/xo-nix3/xo-nix3] in practice)
#      +- repo
#      |  +- xo-cmake/      (source for xo-cmake)
#      |  +- indentlog/     (source for indentlog)
#      |  \- subsys/        (source for subsys)
#      |
#      +- build_xo-cmake/   (build for xo-cmake runs here)
#      +- build_indentlog/  (build for indentlog runs here)
#      +- build_subsys/     (build for subsys runs here)
#      |
#      \- local             (common install prefix)
#         +- share
#         |  \- cmake
#         |     \- xo_macros...
#         +- include
#         |  +- indentlog...
#         |  \- subsys..
#         +- bin
#
# 4. container filesystem
#      |          (root)
#      +- bin...
#      +- lib
#      |  +- cmake
#      |  |  \- Catch2...
#      |  ..
#      +- include/
#      +- share/
#      ..
#
# 5. to invoke cmake build steps,  need to hint container filesystem paths
#    e.g. /lib/cmake for cmake modules
#

name: XO builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build_job:
    name: compile XO projects, using prepared docker container
    runs-on: ubuntu-latest
    container:
      # custom docker image.  see github.com:rconybea/docker-xo-builder for definition
      image: ghcr.io/rconybea/docker-xo-builder:v1
    steps:
      # not using usual checkout actions:  they don't work out-of-the-box from within a container

      # ----------------------------------------------------------------

      - name: prep dir xo-cmake
        run:
          mkdir -p repo/xo-cmake

      - name: checkout xo-cmake
        run:
          GIT_SSL_NO_VERIFY=true git clone https://${{env.GIT_USER}}:${{env.GIT_TOKEN}}@github.com/rconybea/xo-cmake.git repo/xo-cmake

      - name: configure xo-cmake
        run:
          cmake -B ${{github.workspace}}/build_xo-cmake -DCMAKE_MODULE_PATH=/lib/cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/local repo/xo-cmake

      - name: build xo-cmake
        run:
          cmake --build ${{github.workspace}}/build_xo-cmake --config ${{env.BUILD_TYPE}}

      - name: install xo-cmake
        run:
          cmake --install ${{github.workspace}}/build_xo-cmake

      - name: print install tree
        run:
          tree ${{github.workspace}}/local

      - name: print container /include
        run: tree -L 2 --filelimit 10 /include

      - name: print container /lib
        run: tree -L 2 --filelimit 10 /lib
